### ISSUE TITLE
Exceptions thrown by the parser are not properly propagated to output 

### ISSUE THREAD

**Issue by mrkita** [damphyr/rutema#18]
When a test is not marked by "is_special", then exceptions thrown from parsing rutema elements invovled in the test do not appear in the reporting output in useful manner.

This appears to be due to line 77 in engine.rb.

Perhaps the actual problem lies by the error reporting itself.

I am reasonably sure, you can replicate this problem by adding a basic ruby error into a parser rutema extension element.

**Comment by damphyr** [comment]
The final 2.0.0 now fails early on parse errors - any error in a spec in the configuration will end the run.
