### ISSUE TITLE
Rutema together with Ruby 2.3.x creates a stack corruption

### ISSUE THREAD

**Issue by mrkita** [damphyr/rutema#20]
After updating to Ruby 2.3.1 (also tested with 2.3.3.), I found that the configuration file name parsed from the command line, becomes corrupt, after the call on line 205 in configuration.rb to evaluate the ruby content.

If I change the filename argument to __FILE__ everything work. Otherwise, the string becomes corrupted and rutema breaks.

**Comment by damphyr** [comment]
Handled in #21
